### ISSUE TITLE
biotop.owl often defines rdfs:label as asterisk

### ISSUE THREAD

**Issue by rjgladish** [BioTopOntology/biotop#3]
Numerous rdfs labels throughout biotop.owl ontology are defined as an asterisk.
e.g.
SubatomicEntityByChargePartition, StructuredBiologicalCompoundByCanonicityPartition, MolecularEntityByEntiretyPartition, StructuredBiologicalCompoundByGranularityPartition
What is the point? This causes some strange behavior in vocabulary management tools, that expect labels to be meaningful and not use cryptic symbols.

**Comment by steschu63** [comment]
Hello,

thanks for your feedback. The asterisk label was used for classes without
ontological import, which only existed as navigation nodes.
But they don't exist any more aren't you using the current BioTop version. (
purl.org/biotop )

Best regards
Stefan

Am 21.12.2016 03:37 schrieb "rjgladish" <notifications@github.com>:

Numerous rdfs labels throughout biotop.owl ontology are defined as an
asterisk.
e.g.
SubatomicEntityByChargePartition,
StructuredBiologicalCompoundByCanonicityPartition,
MolecularEntityByEntiretyPartition, StructuredBiologicalCompoundBy
GranularityPartition
What is the point? This causes some strange behavior in vocabulary
management tools, that expect labels to be meaningful and not use cryptic
symbols.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/BioTopOntology/biotop/issues/3>, or mute the thread

**Comment by rjgladish** [comment]
I was loading assorted ontologies into a tools that enumerates concept labels to see how robust it was at handling ontologies "in the wild", so your convention "*" to indicate importance,  rather than a declarative property, resulted in the tool reporting numerous concepts with a non-descriptive label. I certainly understand how this occurs in interim versions, but having meaningful labels is helpful. For example, ontologies like bfo/obo have non-intuitive concept uri's (basically numbers), so meaningful labels are critical when used to populate a user interface, or to generate a report. An option menu that displays 17 duplicate labels "*" doesn't go over very well.
